from collections import deque
stack=deque()
stack.append(10)
stack.append(20)
stack.append(30)
stack.append(40)
stack.append(50)
print("stack:",list(stack))
print("Popped element:",stack.pop())
print("stack after pop:",list(stack))